name : demo-actions

on:
  issues:
    types: [opened, edited, milestoned]


jobs:

  my_first_job:
    name: San Luis
    runs-on: ubuntu-latest
    steps:
      - run:  uname -a
      - run: echo " ====== Say Hello from San Luis =========="
      
  
      
  my_second_job:
    name: Jardin
    runs-on: ubuntu-latest
    steps:
      - run: echo "<<<<<< Say Hello from Jardi >>>>>>>"


      
  my_third_job:
    name: Rio Claro
    runs-on: ubuntu-latest
    steps:
      - run: echo "~~~~~~~ Say Hello from Rio Claro ~~~~~~~~~"
